<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>report_feedback_firefox.html</title>
    <link href="assets/style.css" rel="stylesheet" type="text/css"/></head>
  <body onLoad="init()">
    <script>/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */


function toArray(iter) {
    if (iter === null) {
        return null;
    }
    return Array.prototype.slice.call(iter);
}

function find(selector, elem) { // eslint-disable-line no-redeclare
    if (!elem) {
        elem = document;
    }
    return elem.querySelector(selector);
}

function findAll(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return toArray(elem.querySelectorAll(selector));
}

function sortColumn(elem) {
    toggleSortStates(elem);
    const colIndex = toArray(elem.parentNode.childNodes).indexOf(elem);
    let key;
    if (elem.classList.contains('result')) {
        key = keyResult;
    } else if (elem.classList.contains('links')) {
        key = keyLink;
    } else {
        key = keyAlpha;
    }
    sortTable(elem, key(colIndex));
}

function showAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(showExtras);
}

function hideAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(hideExtras);
}

function showExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.remove('collapsed');
    expandcollapse.classList.remove('expander');
    expandcollapse.classList.add('collapser');
}

function hideExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.add('collapsed');
    expandcollapse.classList.remove('collapser');
    expandcollapse.classList.add('expander');
}

function showFilters() {
    let visibleString = getQueryParameter('visible') || 'all';
    visibleString = visibleString.toLowerCase();
    const checkedItems = visibleString.split(',');

    const filterItems = document.getElementsByClassName('filter');
    for (let i = 0; i < filterItems.length; i++) {
        filterItems[i].hidden = false;

        if (visibleString != 'all') {
            filterItems[i].checked = checkedItems.includes(filterItems[i].getAttribute('data-test-result'));
            filterTable(filterItems[i]);
        }
    }
}

function addCollapse() {
    // Add links for show/hide all
    const resulttable = find('table#results-table');
    const showhideall = document.createElement('p');
    showhideall.innerHTML = '<a href="javascript:showAllExtras()">Show all details</a> / ' +
                            '<a href="javascript:hideAllExtras()">Hide all details</a>';
    resulttable.parentElement.insertBefore(showhideall, resulttable);

    // Add show/hide link to each result
    findAll('.col-result').forEach(function(elem) {
        const collapsed = getQueryParameter('collapsed') || 'Passed';
        const extras = elem.parentNode.nextElementSibling;
        const expandcollapse = document.createElement('span');
        if (extras.classList.contains('collapsed')) {
            expandcollapse.classList.add('expander');
        } else if (collapsed.includes(elem.innerHTML)) {
            extras.classList.add('collapsed');
            expandcollapse.classList.add('expander');
        } else {
            expandcollapse.classList.add('collapser');
        }
        elem.appendChild(expandcollapse);

        elem.addEventListener('click', function(event) {
            if (event.currentTarget.parentNode.nextElementSibling.classList.contains('collapsed')) {
                showExtras(event.currentTarget);
            } else {
                hideExtras(event.currentTarget);
            }
        });
    });
}

function getQueryParameter(name) {
    const match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function init () { // eslint-disable-line no-unused-vars
    resetSortHeaders();

    addCollapse();

    showFilters();

    sortColumn(find('.initial-sort'));

    findAll('.sortable').forEach(function(elem) {
        elem.addEventListener('click',
            function() {
                sortColumn(elem);
            }, false);
    });
}

function sortTable(clicked, keyFunc) {
    const rows = findAll('.results-table-row');
    const reversed = !clicked.classList.contains('asc');
    const sortedRows = sort(rows, keyFunc, reversed);
    /* Whole table is removed here because browsers acts much slower
     * when appending existing elements.
     */
    const thead = document.getElementById('results-table-head');
    document.getElementById('results-table').remove();
    const parent = document.createElement('table');
    parent.id = 'results-table';
    parent.appendChild(thead);
    sortedRows.forEach(function(elem) {
        parent.appendChild(elem);
    });
    document.getElementsByTagName('BODY')[0].appendChild(parent);
}

function sort(items, keyFunc, reversed) {
    const sortArray = items.map(function(item, i) {
        return [keyFunc(item), i];
    });

    sortArray.sort(function(a, b) {
        const keyA = a[0];
        const keyB = b[0];

        if (keyA == keyB) return 0;

        if (reversed) {
            return keyA < keyB ? 1 : -1;
        } else {
            return keyA > keyB ? 1 : -1;
        }
    });

    return sortArray.map(function(item) {
        const index = item[1];
        return items[index];
    });
}

function keyAlpha(colIndex) {
    return function(elem) {
        return elem.childNodes[1].childNodes[colIndex].firstChild.data.toLowerCase();
    };
}

function keyLink(colIndex) {
    return function(elem) {
        const dataCell = elem.childNodes[1].childNodes[colIndex].firstChild;
        return dataCell == null ? '' : dataCell.innerText.toLowerCase();
    };
}

function keyResult(colIndex) {
    return function(elem) {
        const strings = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed',
            'Skipped', 'Passed'];
        return strings.indexOf(elem.childNodes[1].childNodes[colIndex].firstChild.data);
    };
}

function resetSortHeaders() {
    findAll('.sort-icon').forEach(function(elem) {
        elem.parentNode.removeChild(elem);
    });
    findAll('.sortable').forEach(function(elem) {
        const icon = document.createElement('div');
        icon.className = 'sort-icon';
        icon.textContent = 'vvv';
        elem.insertBefore(icon, elem.firstChild);
        elem.classList.remove('desc', 'active');
        elem.classList.add('asc', 'inactive');
    });
}

function toggleSortStates(elem) {
    //if active, toggle between asc and desc
    if (elem.classList.contains('active')) {
        elem.classList.toggle('asc');
        elem.classList.toggle('desc');
    }

    //if inactive, reset all other functions and add ascending active
    if (elem.classList.contains('inactive')) {
        resetSortHeaders();
        elem.classList.remove('inactive');
        elem.classList.add('active');
    }
}

function isAllRowsHidden(value) {
    return value.hidden == false;
}

function filterTable(elem) { // eslint-disable-line no-unused-vars
    const outcomeAtt = 'data-test-result';
    const outcome = elem.getAttribute(outcomeAtt);
    const classOutcome = outcome + ' results-table-row';
    const outcomeRows = document.getElementsByClassName(classOutcome);

    for(let i = 0; i < outcomeRows.length; i++){
        outcomeRows[i].hidden = !elem.checked;
    }

    const rows = findAll('.results-table-row').filter(isAllRowsHidden);
    const allRowsHidden = rows.length == 0 ? true : false;
    const notFoundMessage = document.getElementById('not-found-message');
    notFoundMessage.hidden = !allRowsHidden;
}
</script>
    <h1>report_feedback_firefox.html</h1>
    <p>Report generated on 27-Mar-2023 at 22:57:08 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a> v3.2.0</p>
    <h2>Environment</h2>
    <table id="environment">
      <tr>
        <td>JAVA_HOME</td>
        <td>C:\Program Files\Java\jdk-11.0.17</td></tr>
      <tr>
        <td>Packages</td>
        <td>{"pluggy": "1.0.0", "pytest": "7.2.2"}</td></tr>
      <tr>
        <td>Platform</td>
        <td>Windows-10-10.0.19045-SP0</td></tr>
      <tr>
        <td>Plugins</td>
        <td>{"allure-pytest": "2.13.1", "html": "3.2.0", "metadata": "2.0.4", "xdist": "3.2.1"}</td></tr>
      <tr>
        <td>Python</td>
        <td>3.11.2</td></tr></table>
    <h2>Summary</h2>
    <p>10 tests ran in 291.09 seconds. </p>
    <p class="filter" hidden="true">(Un)check the boxes to filter the results.</p><input checked="true" class="filter" data-test-result="passed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="passed">1 passed</span>, <input checked="true" class="filter" data-test-result="skipped" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="skipped">0 skipped</span>, <input checked="true" class="filter" data-test-result="failed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="failed">8 failed</span>, <input checked="true" class="filter" data-test-result="error" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="error">3 errors</span>, <input checked="true" class="filter" data-test-result="xfailed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xfailed">1 expected failures</span>, <input checked="true" class="filter" data-test-result="xpassed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xpassed">0 unexpected passes</span>
    <h2>Results</h2>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable result initial-sort" col="result">Result</th>
          <th class="sortable" col="name">Test</th>
          <th class="sortable" col="duration">Duration</th>
          <th class="sortable links" col="links">Links</th></tr>
        <tr hidden="true" id="not-found-message">
          <th colspan="4">No results found. Try to check the filters</th></tr></thead>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_feedback_form_scale_check[3]::setup</td>
          <td class="col-duration">44.20</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;sqlalchemy.engine.base.Connection object at 0x000001E03A892E50&gt;, engine = Engine(postgresql://postgres:***@localhost:54324/agl_db), connection = None, _has_events = None, _allow_revalidate = True<br/>_allow_autobegin = True<br/><br/>    def __init__(<br/>        self,<br/>        engine: Engine,<br/>        connection: Optional[PoolProxiedConnection] = None,<br/>        _has_events: Optional[bool] = None,<br/>        _allow_revalidate: bool = True,<br/>        _allow_autobegin: bool = True,<br/>    ):<br/>        &quot;&quot;&quot;Construct a new Connection.&quot;&quot;&quot;<br/>        self.engine = engine<br/>        self.dialect = dialect = engine.dialect<br/>    <br/>        if connection is None:<br/>            try:<br/>&gt;               self._dbapi_connection = engine.raw_connection()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:145: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = Engine(postgresql://postgres:***@localhost:54324/agl_db)<br/><br/>    def raw_connection(self) -&gt; PoolProxiedConnection:<br/>        &quot;&quot;&quot;Return a &quot;raw&quot; DBAPI connection from the connection pool.<br/>    <br/>        The returned object is a proxied version of the DBAPI<br/>        connection object used by the underlying driver in use.<br/>        The object will have all the same behavior as the real DBAPI<br/>        connection, except that its ``close()`` method will result in the<br/>        connection being returned to the pool, rather than being closed<br/>        for real.<br/>    <br/>        This method provides direct DBAPI connection access for<br/>        special situations when the API provided by<br/>        :class:`_engine.Connection`<br/>        is not needed.   When a :class:`_engine.Connection` object is already<br/>        present, the DBAPI connection is available using<br/>        the :attr:`_engine.Connection.connection` accessor.<br/>    <br/>        .. seealso::<br/>    <br/>            :ref:`dbapi_connections`<br/>    <br/>        &quot;&quot;&quot;<br/>&gt;       return self.pool.connect()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:3275: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03A95F550&gt;<br/><br/>    def connect(self) -&gt; PoolProxiedConnection:<br/>        &quot;&quot;&quot;Return a DBAPI connection from the pool.<br/>    <br/>        The connection is instrumented such that when its<br/>        ``close()`` method is called, the connection will be returned to<br/>        the pool.<br/>    <br/>        &quot;&quot;&quot;<br/>&gt;       return _ConnectionFairy._checkout(self)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:455: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>cls = &lt;class &#x27;sqlalchemy.pool.base._ConnectionFairy&#x27;&gt;, pool = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03A95F550&gt;, threadconns = None, fairy = None<br/><br/>    @classmethod<br/>    def _checkout(<br/>        cls,<br/>        pool: Pool,<br/>        threadconns: Optional[threading.local] = None,<br/>        fairy: Optional[_ConnectionFairy] = None,<br/>    ) -&gt; _ConnectionFairy:<br/>    <br/>        if not fairy:<br/>&gt;           fairy = _ConnectionRecord.checkout(pool)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:1271: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>cls = &lt;class &#x27;sqlalchemy.pool.base._ConnectionRecord&#x27;&gt;, pool = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03A95F550&gt;<br/><br/>    @classmethod<br/>    def checkout(cls, pool: Pool) -&gt; _ConnectionFairy:<br/>        if TYPE_CHECKING:<br/>            rec = cast(_ConnectionRecord, pool._do_get())<br/>        else:<br/>&gt;           rec = pool._do_get()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:719: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03A95F550&gt;<br/><br/>    def _do_get(self) -&gt; ConnectionPoolEntry:<br/>        use_overflow = self._max_overflow &gt; -1<br/>    <br/>        wait = use_overflow and self._overflow &gt;= self._max_overflow<br/>        try:<br/>            return self._pool.get(wait, self._timeout)<br/>        except sqla_queue.Empty:<br/>            # don&#x27;t do things inside of &quot;except Empty&quot;, because when we say<br/>            # we timed out or can&#x27;t connect and raise, Python 3 tells<br/>            # people the real error is queue.Empty which it isn&#x27;t.<br/>            pass<br/>        if use_overflow and self._overflow &gt;= self._max_overflow:<br/>            if not wait:<br/>                return self._do_get()<br/>            else:<br/>                raise exc.TimeoutError(<br/>                    &quot;QueuePool limit of size %d overflow %d reached, &quot;<br/>                    &quot;connection timed out, timeout %0.2f&quot;<br/>                    % (self.size(), self.overflow(), self._timeout),<br/>                    code=&quot;3o7r&quot;,<br/>                )<br/>    <br/>        if self._inc_overflow():<br/>            try:<br/>                return self._create_connection()<br/>            except:<br/>&gt;               with util.safe_reraise():<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\impl.py:168: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.util.langhelpers.safe_reraise object at 0x000001E03A88E260&gt;, type_ = None, value = None, traceback = None<br/><br/>    def __exit__(<br/>        self,<br/>        type_: Optional[Type[BaseException]],<br/>        value: Optional[BaseException],<br/>        traceback: Optional[types.TracebackType],<br/>    ) -&gt; NoReturn:<br/>        assert self._exc_info is not None<br/>        # see #2703 for notes<br/>        if type_ is None:<br/>            exc_type, exc_value, exc_tb = self._exc_info<br/>            assert exc_value is not None<br/>            self._exc_info = None  # remove potential circular references<br/>&gt;           raise exc_value.with_traceback(exc_tb)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py:147: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03A95F550&gt;<br/><br/>    def _do_get(self) -&gt; ConnectionPoolEntry:<br/>        use_overflow = self._max_overflow &gt; -1<br/>    <br/>        wait = use_overflow and self._overflow &gt;= self._max_overflow<br/>        try:<br/>            return self._pool.get(wait, self._timeout)<br/>        except sqla_queue.Empty:<br/>            # don&#x27;t do things inside of &quot;except Empty&quot;, because when we say<br/>            # we timed out or can&#x27;t connect and raise, Python 3 tells<br/>            # people the real error is queue.Empty which it isn&#x27;t.<br/>            pass<br/>        if use_overflow and self._overflow &gt;= self._max_overflow:<br/>            if not wait:<br/>                return self._do_get()<br/>            else:<br/>                raise exc.TimeoutError(<br/>                    &quot;QueuePool limit of size %d overflow %d reached, &quot;<br/>                    &quot;connection timed out, timeout %0.2f&quot;<br/>                    % (self.size(), self.overflow(), self._timeout),<br/>                    code=&quot;3o7r&quot;,<br/>                )<br/>    <br/>        if self._inc_overflow():<br/>            try:<br/>&gt;               return self._create_connection()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\impl.py:166: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03A95F550&gt;<br/><br/>    def _create_connection(self) -&gt; ConnectionPoolEntry:<br/>        &quot;&quot;&quot;Called by subclasses to create a new ConnectionRecord.&quot;&quot;&quot;<br/>    <br/>&gt;       return _ConnectionRecord(self)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:396: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.base._ConnectionRecord object at 0x000001E03A8E6F20&gt;, pool = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03A95F550&gt;, connect = True<br/><br/>    def __init__(self, pool: Pool, connect: bool = True):<br/>        self.fresh = False<br/>        self.fairy_ref = None<br/>        self.starttime = 0<br/>        self.dbapi_connection = None<br/>    <br/>        self.__pool = pool<br/>        if connect:<br/>&gt;           self.__connect()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:681: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.base._ConnectionRecord object at 0x000001E03A8E6F20&gt;<br/><br/>    def __connect(self) -&gt; None:<br/>        pool = self.__pool<br/>    <br/>        # ensure any existing connection is removed, so that if<br/>        # creator fails, this attribute stays None<br/>        self.dbapi_connection = None<br/>        try:<br/>            self.starttime = time.time()<br/>            self.dbapi_connection = connection = pool._invoke_creator(self)<br/>            pool.logger.debug(&quot;Created new connection %r&quot;, connection)<br/>            self.fresh = True<br/>        except BaseException as e:<br/>&gt;           with util.safe_reraise():<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:905: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.util.langhelpers.safe_reraise object at 0x000001E03A88E320&gt;, type_ = None, value = None, traceback = None<br/><br/>    def __exit__(<br/>        self,<br/>        type_: Optional[Type[BaseException]],<br/>        value: Optional[BaseException],<br/>        traceback: Optional[types.TracebackType],<br/>    ) -&gt; NoReturn:<br/>        assert self._exc_info is not None<br/>        # see #2703 for notes<br/>        if type_ is None:<br/>            exc_type, exc_value, exc_tb = self._exc_info<br/>            assert exc_value is not None<br/>            self._exc_info = None  # remove potential circular references<br/>&gt;           raise exc_value.with_traceback(exc_tb)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py:147: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.base._ConnectionRecord object at 0x000001E03A8E6F20&gt;<br/><br/>    def __connect(self) -&gt; None:<br/>        pool = self.__pool<br/>    <br/>        # ensure any existing connection is removed, so that if<br/>        # creator fails, this attribute stays None<br/>        self.dbapi_connection = None<br/>        try:<br/>            self.starttime = time.time()<br/>&gt;           self.dbapi_connection = connection = pool._invoke_creator(self)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:901: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>connection_record = &lt;sqlalchemy.pool.base._ConnectionRecord object at 0x000001E03A8E6F20&gt;<br/><br/>    def connect(<br/>        connection_record: Optional[ConnectionPoolEntry] = None,<br/>    ) -&gt; DBAPIConnection:<br/>        if dialect._has_events:<br/>            for fn in dialect.dispatch.do_connect:<br/>                connection = cast(<br/>                    DBAPIConnection,<br/>                    fn(dialect, connection_record, cargs, cparams),<br/>                )<br/>                if connection is not None:<br/>                    return connection<br/>    <br/>&gt;       return dialect.connect(*cargs, **cparams)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\create.py:636: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x000001E03A95CB50&gt;, cargs = (), cparams = {&#x27;dbname&#x27;: &#x27;agl_db&#x27;, &#x27;host&#x27;: &#x27;localhost&#x27;, &#x27;password&#x27;: &#x27;postgres&#x27;, &#x27;port&#x27;: 54324, ...}<br/><br/>    def connect(self, *cargs, **cparams):<br/>        # inherits the docstring from interfaces.Dialect.connect<br/>&gt;       return self.loaded_dbapi.connect(*cargs, **cparams)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py:580: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>dsn = &#x27;host=localhost dbname=agl_db user=postgres password=postgres port=54324&#x27;, connection_factory = None, cursor_factory = None, kwargs = {&#x27;dbname&#x27;: &#x27;agl_db&#x27;, &#x27;host&#x27;: &#x27;localhost&#x27;, &#x27;password&#x27;: &#x27;postgres&#x27;, &#x27;port&#x27;: 54324, ...}<br/>kwasync = {}<br/><br/>    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):<br/>        &quot;&quot;&quot;<br/>        Create a new database connection.<br/>    <br/>        The connection parameters can be specified as a string:<br/>    <br/>            conn = psycopg2.connect(&quot;dbname=test user=postgres password=secret&quot;)<br/>    <br/>        or using a set of keyword arguments:<br/>    <br/>            conn = psycopg2.connect(database=&quot;test&quot;, user=&quot;postgres&quot;, password=&quot;secret&quot;)<br/>    <br/>        Or as a mix of both. The basic connection parameters are:<br/>    <br/>        - *dbname*: the database name<br/>        - *database*: the database name (only as keyword argument)<br/>        - *user*: user name used to authenticate<br/>        - *password*: password used to authenticate<br/>        - *host*: database host address (defaults to UNIX socket if not provided)<br/>        - *port*: connection port number (defaults to 5432 if not provided)<br/>    <br/>        Using the *connection_factory* parameter a different class or connections<br/>        factory can be specified. It should be a callable object taking a dsn<br/>        argument.<br/>    <br/>        Using the *cursor_factory* parameter, a new default cursor factory will be<br/>        used by cursor().<br/>    <br/>        Using *async*=True an asynchronous connection will be created. *async_* is<br/>        a valid alias (for Python versions where ``async`` is a keyword).<br/>    <br/>        Any other keyword parameter will be passed to the underlying client<br/>        library: the list of supported parameters depends on the library version.<br/>    <br/>        &quot;&quot;&quot;<br/>        kwasync = {}<br/>        if &#x27;async&#x27; in kwargs:<br/>            kwasync[&#x27;async&#x27;] = kwargs.pop(&#x27;async&#x27;)<br/>        if &#x27;async_&#x27; in kwargs:<br/>            kwasync[&#x27;async_&#x27;] = kwargs.pop(&#x27;async_&#x27;)<br/>    <br/>        dsn = _ext.make_dsn(dsn, **kwargs)<br/>&gt;       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)<br/><span class="error">E       psycopg2.OperationalError: connection to server at &quot;localhost&quot; (::1), port 54324 failed: server closed the connection unexpectedly</span><br/><span class="error">E       	This probably means the server terminated abnormally</span><br/><span class="error">E       	before or while processing the request.</span><br/><br/>F:\Programs\Python\Python311\Lib\site-packages\psycopg2\__init__.py:122: OperationalError<br/><br/>The above exception was the direct cause of the following exception:<br/><br/>    @pytest.fixture(scope=&#x27;function&#x27;)<br/>    def feedback_database_setup():<br/>        # DB connect:<br/>        engine = create_engine(&#x27;postgresql://postgres:postgres@localhost:54324/agl_db&#x27;)<br/>&gt;       connection = engine.connect()<br/><br/>conftest.py:182: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:3251: in connect<br/>    return self._connection_cls(self)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:147: in __init__<br/>    Connection._handle_dbapi_exception_noconnection(<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:2413: in _handle_dbapi_exception_noconnection<br/>    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:145: in __init__<br/>    self._dbapi_connection = engine.raw_connection()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:3275: in raw_connection<br/>    return self.pool.connect()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:455: in connect<br/>    return _ConnectionFairy._checkout(self)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:1271: in _checkout<br/>    fairy = _ConnectionRecord.checkout(pool)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:719: in checkout<br/>    rec = pool._do_get()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\impl.py:168: in _do_get<br/>    with util.safe_reraise():<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py:147: in __exit__<br/>    raise exc_value.with_traceback(exc_tb)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\impl.py:166: in _do_get<br/>    return self._create_connection()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:396: in _create_connection<br/>    return _ConnectionRecord(self)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:681: in __init__<br/>    self.__connect()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:905: in __connect<br/>    with util.safe_reraise():<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py:147: in __exit__<br/>    raise exc_value.with_traceback(exc_tb)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:901: in __connect<br/>    self.dbapi_connection = connection = pool._invoke_creator(self)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\create.py:636: in connect<br/>    return dialect.connect(*cargs, **cparams)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py:580: in connect<br/>    return self.loaded_dbapi.connect(*cargs, **cparams)<br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>dsn = &#x27;host=localhost dbname=agl_db user=postgres password=postgres port=54324&#x27;, connection_factory = None, cursor_factory = None, kwargs = {&#x27;dbname&#x27;: &#x27;agl_db&#x27;, &#x27;host&#x27;: &#x27;localhost&#x27;, &#x27;password&#x27;: &#x27;postgres&#x27;, &#x27;port&#x27;: 54324, ...}<br/>kwasync = {}<br/><br/>    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):<br/>        &quot;&quot;&quot;<br/>        Create a new database connection.<br/>    <br/>        The connection parameters can be specified as a string:<br/>    <br/>            conn = psycopg2.connect(&quot;dbname=test user=postgres password=secret&quot;)<br/>    <br/>        or using a set of keyword arguments:<br/>    <br/>            conn = psycopg2.connect(database=&quot;test&quot;, user=&quot;postgres&quot;, password=&quot;secret&quot;)<br/>    <br/>        Or as a mix of both. The basic connection parameters are:<br/>    <br/>        - *dbname*: the database name<br/>        - *database*: the database name (only as keyword argument)<br/>        - *user*: user name used to authenticate<br/>        - *password*: password used to authenticate<br/>        - *host*: database host address (defaults to UNIX socket if not provided)<br/>        - *port*: connection port number (defaults to 5432 if not provided)<br/>    <br/>        Using the *connection_factory* parameter a different class or connections<br/>        factory can be specified. It should be a callable object taking a dsn<br/>        argument.<br/>    <br/>        Using the *cursor_factory* parameter, a new default cursor factory will be<br/>        used by cursor().<br/>    <br/>        Using *async*=True an asynchronous connection will be created. *async_* is<br/>        a valid alias (for Python versions where ``async`` is a keyword).<br/>    <br/>        Any other keyword parameter will be passed to the underlying client<br/>        library: the list of supported parameters depends on the library version.<br/>    <br/>        &quot;&quot;&quot;<br/>        kwasync = {}<br/>        if &#x27;async&#x27; in kwargs:<br/>            kwasync[&#x27;async&#x27;] = kwargs.pop(&#x27;async&#x27;)<br/>        if &#x27;async_&#x27; in kwargs:<br/>            kwasync[&#x27;async_&#x27;] = kwargs.pop(&#x27;async_&#x27;)<br/>    <br/>        dsn = _ext.make_dsn(dsn, **kwargs)<br/>&gt;       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)<br/><span class="error">E       sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at &quot;localhost&quot; (::1), port 54324 failed: server closed the connection unexpectedly</span><br/><span class="error">E       	This probably means the server terminated abnormally</span><br/><span class="error">E       	before or while processing the request.</span><br/><span class="error">E       </span><br/><span class="error">E       (Background on this error at: https://sqlalche.me/e/20/e3q8)</span><br/><br/>F:\Programs\Python\Python311\Lib\site-packages\psycopg2\__init__.py:122: OperationalError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_feedback_form_scale_check[5]::setup</td>
          <td class="col-duration">43.83</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;sqlalchemy.engine.base.Connection object at 0x000001E03B00CC90&gt;, engine = Engine(postgresql://postgres:***@localhost:54324/agl_db), connection = None, _has_events = None, _allow_revalidate = True<br/>_allow_autobegin = True<br/><br/>    def __init__(<br/>        self,<br/>        engine: Engine,<br/>        connection: Optional[PoolProxiedConnection] = None,<br/>        _has_events: Optional[bool] = None,<br/>        _allow_revalidate: bool = True,<br/>        _allow_autobegin: bool = True,<br/>    ):<br/>        &quot;&quot;&quot;Construct a new Connection.&quot;&quot;&quot;<br/>        self.engine = engine<br/>        self.dialect = dialect = engine.dialect<br/>    <br/>        if connection is None:<br/>            try:<br/>&gt;               self._dbapi_connection = engine.raw_connection()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:145: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = Engine(postgresql://postgres:***@localhost:54324/agl_db)<br/><br/>    def raw_connection(self) -&gt; PoolProxiedConnection:<br/>        &quot;&quot;&quot;Return a &quot;raw&quot; DBAPI connection from the connection pool.<br/>    <br/>        The returned object is a proxied version of the DBAPI<br/>        connection object used by the underlying driver in use.<br/>        The object will have all the same behavior as the real DBAPI<br/>        connection, except that its ``close()`` method will result in the<br/>        connection being returned to the pool, rather than being closed<br/>        for real.<br/>    <br/>        This method provides direct DBAPI connection access for<br/>        special situations when the API provided by<br/>        :class:`_engine.Connection`<br/>        is not needed.   When a :class:`_engine.Connection` object is already<br/>        present, the DBAPI connection is available using<br/>        the :attr:`_engine.Connection.connection` accessor.<br/>    <br/>        .. seealso::<br/>    <br/>            :ref:`dbapi_connections`<br/>    <br/>        &quot;&quot;&quot;<br/>&gt;       return self.pool.connect()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:3275: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03B00E0D0&gt;<br/><br/>    def connect(self) -&gt; PoolProxiedConnection:<br/>        &quot;&quot;&quot;Return a DBAPI connection from the pool.<br/>    <br/>        The connection is instrumented such that when its<br/>        ``close()`` method is called, the connection will be returned to<br/>        the pool.<br/>    <br/>        &quot;&quot;&quot;<br/>&gt;       return _ConnectionFairy._checkout(self)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:455: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>cls = &lt;class &#x27;sqlalchemy.pool.base._ConnectionFairy&#x27;&gt;, pool = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03B00E0D0&gt;, threadconns = None, fairy = None<br/><br/>    @classmethod<br/>    def _checkout(<br/>        cls,<br/>        pool: Pool,<br/>        threadconns: Optional[threading.local] = None,<br/>        fairy: Optional[_ConnectionFairy] = None,<br/>    ) -&gt; _ConnectionFairy:<br/>    <br/>        if not fairy:<br/>&gt;           fairy = _ConnectionRecord.checkout(pool)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:1271: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>cls = &lt;class &#x27;sqlalchemy.pool.base._ConnectionRecord&#x27;&gt;, pool = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03B00E0D0&gt;<br/><br/>    @classmethod<br/>    def checkout(cls, pool: Pool) -&gt; _ConnectionFairy:<br/>        if TYPE_CHECKING:<br/>            rec = cast(_ConnectionRecord, pool._do_get())<br/>        else:<br/>&gt;           rec = pool._do_get()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:719: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03B00E0D0&gt;<br/><br/>    def _do_get(self) -&gt; ConnectionPoolEntry:<br/>        use_overflow = self._max_overflow &gt; -1<br/>    <br/>        wait = use_overflow and self._overflow &gt;= self._max_overflow<br/>        try:<br/>            return self._pool.get(wait, self._timeout)<br/>        except sqla_queue.Empty:<br/>            # don&#x27;t do things inside of &quot;except Empty&quot;, because when we say<br/>            # we timed out or can&#x27;t connect and raise, Python 3 tells<br/>            # people the real error is queue.Empty which it isn&#x27;t.<br/>            pass<br/>        if use_overflow and self._overflow &gt;= self._max_overflow:<br/>            if not wait:<br/>                return self._do_get()<br/>            else:<br/>                raise exc.TimeoutError(<br/>                    &quot;QueuePool limit of size %d overflow %d reached, &quot;<br/>                    &quot;connection timed out, timeout %0.2f&quot;<br/>                    % (self.size(), self.overflow(), self._timeout),<br/>                    code=&quot;3o7r&quot;,<br/>                )<br/>    <br/>        if self._inc_overflow():<br/>            try:<br/>                return self._create_connection()<br/>            except:<br/>&gt;               with util.safe_reraise():<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\impl.py:168: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.util.langhelpers.safe_reraise object at 0x000001E03AE76FE0&gt;, type_ = None, value = None, traceback = None<br/><br/>    def __exit__(<br/>        self,<br/>        type_: Optional[Type[BaseException]],<br/>        value: Optional[BaseException],<br/>        traceback: Optional[types.TracebackType],<br/>    ) -&gt; NoReturn:<br/>        assert self._exc_info is not None<br/>        # see #2703 for notes<br/>        if type_ is None:<br/>            exc_type, exc_value, exc_tb = self._exc_info<br/>            assert exc_value is not None<br/>            self._exc_info = None  # remove potential circular references<br/>&gt;           raise exc_value.with_traceback(exc_tb)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py:147: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03B00E0D0&gt;<br/><br/>    def _do_get(self) -&gt; ConnectionPoolEntry:<br/>        use_overflow = self._max_overflow &gt; -1<br/>    <br/>        wait = use_overflow and self._overflow &gt;= self._max_overflow<br/>        try:<br/>            return self._pool.get(wait, self._timeout)<br/>        except sqla_queue.Empty:<br/>            # don&#x27;t do things inside of &quot;except Empty&quot;, because when we say<br/>            # we timed out or can&#x27;t connect and raise, Python 3 tells<br/>            # people the real error is queue.Empty which it isn&#x27;t.<br/>            pass<br/>        if use_overflow and self._overflow &gt;= self._max_overflow:<br/>            if not wait:<br/>                return self._do_get()<br/>            else:<br/>                raise exc.TimeoutError(<br/>                    &quot;QueuePool limit of size %d overflow %d reached, &quot;<br/>                    &quot;connection timed out, timeout %0.2f&quot;<br/>                    % (self.size(), self.overflow(), self._timeout),<br/>                    code=&quot;3o7r&quot;,<br/>                )<br/>    <br/>        if self._inc_overflow():<br/>            try:<br/>&gt;               return self._create_connection()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\impl.py:166: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03B00E0D0&gt;<br/><br/>    def _create_connection(self) -&gt; ConnectionPoolEntry:<br/>        &quot;&quot;&quot;Called by subclasses to create a new ConnectionRecord.&quot;&quot;&quot;<br/>    <br/>&gt;       return _ConnectionRecord(self)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:396: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.base._ConnectionRecord object at 0x000001E03B0DD240&gt;, pool = &lt;sqlalchemy.pool.impl.QueuePool object at 0x000001E03B00E0D0&gt;, connect = True<br/><br/>    def __init__(self, pool: Pool, connect: bool = True):<br/>        self.fresh = False<br/>        self.fairy_ref = None<br/>        self.starttime = 0<br/>        self.dbapi_connection = None<br/>    <br/>        self.__pool = pool<br/>        if connect:<br/>&gt;           self.__connect()<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:681: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.base._ConnectionRecord object at 0x000001E03B0DD240&gt;<br/><br/>    def __connect(self) -&gt; None:<br/>        pool = self.__pool<br/>    <br/>        # ensure any existing connection is removed, so that if<br/>        # creator fails, this attribute stays None<br/>        self.dbapi_connection = None<br/>        try:<br/>            self.starttime = time.time()<br/>            self.dbapi_connection = connection = pool._invoke_creator(self)<br/>            pool.logger.debug(&quot;Created new connection %r&quot;, connection)<br/>            self.fresh = True<br/>        except BaseException as e:<br/>&gt;           with util.safe_reraise():<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:905: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.util.langhelpers.safe_reraise object at 0x000001E03AE75A80&gt;, type_ = None, value = None, traceback = None<br/><br/>    def __exit__(<br/>        self,<br/>        type_: Optional[Type[BaseException]],<br/>        value: Optional[BaseException],<br/>        traceback: Optional[types.TracebackType],<br/>    ) -&gt; NoReturn:<br/>        assert self._exc_info is not None<br/>        # see #2703 for notes<br/>        if type_ is None:<br/>            exc_type, exc_value, exc_tb = self._exc_info<br/>            assert exc_value is not None<br/>            self._exc_info = None  # remove potential circular references<br/>&gt;           raise exc_value.with_traceback(exc_tb)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py:147: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.pool.base._ConnectionRecord object at 0x000001E03B0DD240&gt;<br/><br/>    def __connect(self) -&gt; None:<br/>        pool = self.__pool<br/>    <br/>        # ensure any existing connection is removed, so that if<br/>        # creator fails, this attribute stays None<br/>        self.dbapi_connection = None<br/>        try:<br/>            self.starttime = time.time()<br/>&gt;           self.dbapi_connection = connection = pool._invoke_creator(self)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:901: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>connection_record = &lt;sqlalchemy.pool.base._ConnectionRecord object at 0x000001E03B0DD240&gt;<br/><br/>    def connect(<br/>        connection_record: Optional[ConnectionPoolEntry] = None,<br/>    ) -&gt; DBAPIConnection:<br/>        if dialect._has_events:<br/>            for fn in dialect.dispatch.do_connect:<br/>                connection = cast(<br/>                    DBAPIConnection,<br/>                    fn(dialect, connection_record, cargs, cparams),<br/>                )<br/>                if connection is not None:<br/>                    return connection<br/>    <br/>&gt;       return dialect.connect(*cargs, **cparams)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\create.py:636: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x000001E03B00EE90&gt;, cargs = (), cparams = {&#x27;dbname&#x27;: &#x27;agl_db&#x27;, &#x27;host&#x27;: &#x27;localhost&#x27;, &#x27;password&#x27;: &#x27;postgres&#x27;, &#x27;port&#x27;: 54324, ...}<br/><br/>    def connect(self, *cargs, **cparams):<br/>        # inherits the docstring from interfaces.Dialect.connect<br/>&gt;       return self.loaded_dbapi.connect(*cargs, **cparams)<br/><br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py:580: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>dsn = &#x27;host=localhost dbname=agl_db user=postgres password=postgres port=54324&#x27;, connection_factory = None, cursor_factory = None, kwargs = {&#x27;dbname&#x27;: &#x27;agl_db&#x27;, &#x27;host&#x27;: &#x27;localhost&#x27;, &#x27;password&#x27;: &#x27;postgres&#x27;, &#x27;port&#x27;: 54324, ...}<br/>kwasync = {}<br/><br/>    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):<br/>        &quot;&quot;&quot;<br/>        Create a new database connection.<br/>    <br/>        The connection parameters can be specified as a string:<br/>    <br/>            conn = psycopg2.connect(&quot;dbname=test user=postgres password=secret&quot;)<br/>    <br/>        or using a set of keyword arguments:<br/>    <br/>            conn = psycopg2.connect(database=&quot;test&quot;, user=&quot;postgres&quot;, password=&quot;secret&quot;)<br/>    <br/>        Or as a mix of both. The basic connection parameters are:<br/>    <br/>        - *dbname*: the database name<br/>        - *database*: the database name (only as keyword argument)<br/>        - *user*: user name used to authenticate<br/>        - *password*: password used to authenticate<br/>        - *host*: database host address (defaults to UNIX socket if not provided)<br/>        - *port*: connection port number (defaults to 5432 if not provided)<br/>    <br/>        Using the *connection_factory* parameter a different class or connections<br/>        factory can be specified. It should be a callable object taking a dsn<br/>        argument.<br/>    <br/>        Using the *cursor_factory* parameter, a new default cursor factory will be<br/>        used by cursor().<br/>    <br/>        Using *async*=True an asynchronous connection will be created. *async_* is<br/>        a valid alias (for Python versions where ``async`` is a keyword).<br/>    <br/>        Any other keyword parameter will be passed to the underlying client<br/>        library: the list of supported parameters depends on the library version.<br/>    <br/>        &quot;&quot;&quot;<br/>        kwasync = {}<br/>        if &#x27;async&#x27; in kwargs:<br/>            kwasync[&#x27;async&#x27;] = kwargs.pop(&#x27;async&#x27;)<br/>        if &#x27;async_&#x27; in kwargs:<br/>            kwasync[&#x27;async_&#x27;] = kwargs.pop(&#x27;async_&#x27;)<br/>    <br/>        dsn = _ext.make_dsn(dsn, **kwargs)<br/>&gt;       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)<br/><span class="error">E       psycopg2.OperationalError: connection to server at &quot;localhost&quot; (::1), port 54324 failed: server closed the connection unexpectedly</span><br/><span class="error">E       	This probably means the server terminated abnormally</span><br/><span class="error">E       	before or while processing the request.</span><br/><br/>F:\Programs\Python\Python311\Lib\site-packages\psycopg2\__init__.py:122: OperationalError<br/><br/>The above exception was the direct cause of the following exception:<br/><br/>    @pytest.fixture(scope=&#x27;function&#x27;)<br/>    def feedback_database_setup():<br/>        # DB connect:<br/>        engine = create_engine(&#x27;postgresql://postgres:postgres@localhost:54324/agl_db&#x27;)<br/>&gt;       connection = engine.connect()<br/><br/>conftest.py:182: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:3251: in connect<br/>    return self._connection_cls(self)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:147: in __init__<br/>    Connection._handle_dbapi_exception_noconnection(<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:2413: in _handle_dbapi_exception_noconnection<br/>    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:145: in __init__<br/>    self._dbapi_connection = engine.raw_connection()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py:3275: in raw_connection<br/>    return self.pool.connect()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:455: in connect<br/>    return _ConnectionFairy._checkout(self)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:1271: in _checkout<br/>    fairy = _ConnectionRecord.checkout(pool)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:719: in checkout<br/>    rec = pool._do_get()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\impl.py:168: in _do_get<br/>    with util.safe_reraise():<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py:147: in __exit__<br/>    raise exc_value.with_traceback(exc_tb)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\impl.py:166: in _do_get<br/>    return self._create_connection()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:396: in _create_connection<br/>    return _ConnectionRecord(self)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:681: in __init__<br/>    self.__connect()<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:905: in __connect<br/>    with util.safe_reraise():<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py:147: in __exit__<br/>    raise exc_value.with_traceback(exc_tb)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py:901: in __connect<br/>    self.dbapi_connection = connection = pool._invoke_creator(self)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\create.py:636: in connect<br/>    return dialect.connect(*cargs, **cparams)<br/>F:\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py:580: in connect<br/>    return self.loaded_dbapi.connect(*cargs, **cparams)<br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>dsn = &#x27;host=localhost dbname=agl_db user=postgres password=postgres port=54324&#x27;, connection_factory = None, cursor_factory = None, kwargs = {&#x27;dbname&#x27;: &#x27;agl_db&#x27;, &#x27;host&#x27;: &#x27;localhost&#x27;, &#x27;password&#x27;: &#x27;postgres&#x27;, &#x27;port&#x27;: 54324, ...}<br/>kwasync = {}<br/><br/>    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):<br/>        &quot;&quot;&quot;<br/>        Create a new database connection.<br/>    <br/>        The connection parameters can be specified as a string:<br/>    <br/>            conn = psycopg2.connect(&quot;dbname=test user=postgres password=secret&quot;)<br/>    <br/>        or using a set of keyword arguments:<br/>    <br/>            conn = psycopg2.connect(database=&quot;test&quot;, user=&quot;postgres&quot;, password=&quot;secret&quot;)<br/>    <br/>        Or as a mix of both. The basic connection parameters are:<br/>    <br/>        - *dbname*: the database name<br/>        - *database*: the database name (only as keyword argument)<br/>        - *user*: user name used to authenticate<br/>        - *password*: password used to authenticate<br/>        - *host*: database host address (defaults to UNIX socket if not provided)<br/>        - *port*: connection port number (defaults to 5432 if not provided)<br/>    <br/>        Using the *connection_factory* parameter a different class or connections<br/>        factory can be specified. It should be a callable object taking a dsn<br/>        argument.<br/>    <br/>        Using the *cursor_factory* parameter, a new default cursor factory will be<br/>        used by cursor().<br/>    <br/>        Using *async*=True an asynchronous connection will be created. *async_* is<br/>        a valid alias (for Python versions where ``async`` is a keyword).<br/>    <br/>        Any other keyword parameter will be passed to the underlying client<br/>        library: the list of supported parameters depends on the library version.<br/>    <br/>        &quot;&quot;&quot;<br/>        kwasync = {}<br/>        if &#x27;async&#x27; in kwargs:<br/>            kwasync[&#x27;async&#x27;] = kwargs.pop(&#x27;async&#x27;)<br/>        if &#x27;async_&#x27; in kwargs:<br/>            kwasync[&#x27;async_&#x27;] = kwargs.pop(&#x27;async_&#x27;)<br/>    <br/>        dsn = _ext.make_dsn(dsn, **kwargs)<br/>&gt;       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)<br/><span class="error">E       sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at &quot;localhost&quot; (::1), port 54324 failed: server closed the connection unexpectedly</span><br/><span class="error">E       	This probably means the server terminated abnormally</span><br/><span class="error">E       	before or while processing the request.</span><br/><span class="error">E       </span><br/><span class="error">E       (Background on this error at: https://sqlalche.me/e/20/e3q8)</span><br/><br/>F:\Programs\Python\Python311\Lib\site-packages\psycopg2\__init__.py:122: OperationalError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, 1.14MB/s]                                                                                                                                                                                   
<br/></div></td></tr></tbody>
      <tbody class="error results-table-row">
        <tr>
          <td class="col-result">Error</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_5246_feedback_input_allowed_limit[254]::setup</td>
          <td class="col-duration">12.67</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;66096a16-0c17-46bd-ad69-dd6e3cdce429&quot;)&gt;<br/><br/>    @pytest.fixture(scope=&quot;function&quot;)<br/>    def retro(browser):<br/>        wait = WebDriverWait(browser, 20)<br/>    <br/>        # Open http://localhost:3000/:<br/>        browser.get(link_home)<br/>    <br/>        # Fill in &quot;Email&quot; field:<br/>        wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;input[placeholder=&quot;Enter Your Email&quot;]&#x27;))<br/>        ).send_keys(users_parser()[&#x27;email_1&#x27;])<br/>    <br/>    <br/>        # Fill in &quot;Password&quot; field:<br/>        browser.find_element(By.CSS_SELECTOR, &#x27;input[placeholder=&quot;Enter Your Password&quot;]&#x27;)\<br/>            .send_keys(&#x27;Godfather1989!&#x27;)<br/>    <br/>        # Click &quot;Sign in&quot; button:<br/>        browser.find_element(By.CSS_SELECTOR, &#x27;.Button__button.Button__blue.styles__actionButton&#x27;).click()<br/>    <br/>        # Wait for &quot;Not Found&quot; button to be displayed:<br/>        wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;div[role=&quot;alert&quot;]&#x27;)<br/>        ))<br/>    <br/>        # Close &quot;Not Found&quot; alert:<br/>        if len(browser.find_elements(By.CSS_SELECTOR, &#x27;div[role=&quot;alert&quot;]&#x27;)) != 0:<br/>            alert = browser.find_element(By.CSS_SELECTOR, &#x27;div[role=&quot;alert&quot;] &gt; div &gt; button&#x27;)<br/>            browser.execute_script(&quot;arguments[0].scrollIntoView();&quot;, alert)<br/>&gt;           alert.click()<br/><br/>conftest.py:96: <br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/>F:\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py:94: in click<br/>    self._execute(Command.CLICK_ELEMENT)<br/>F:\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py:404: in _execute<br/>    return self._parent.execute(command, params)<br/>F:\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py:440: in execute<br/>    self.error_handler.check_response(response)<br/>_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ <br/><br/>self = &lt;selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000001E03A9042D0&gt;<br/>response = {&#x27;status&#x27;: 400, &#x27;value&#x27;: &#x27;{&quot;value&quot;:{&quot;error&quot;:&quot;element not interactable&quot;,&quot;message&quot;:&quot;Element &lt;button class=\\&quot;_35coK uui-...sys.mjs:208:29\\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:97:31\\n&quot;}}&#x27;}<br/><br/>    def check_response(self, response: Dict[str, Any]) -&gt; None:<br/>        &quot;&quot;&quot;Checks that a JSON response from the WebDriver does not have an<br/>        error.<br/>    <br/>        :Args:<br/>         - response - The JSON response from the WebDriver server as a dictionary<br/>           object.<br/>    <br/>        :Raises: If the response contains an error message.<br/>        &quot;&quot;&quot;<br/>        status = response.get(&quot;status&quot;, None)<br/>        if not status or status == ErrorCode.SUCCESS:<br/>            return<br/>        value = None<br/>        message = response.get(&quot;message&quot;, &quot;&quot;)<br/>        screen: str = response.get(&quot;screen&quot;, &quot;&quot;)<br/>        stacktrace = None<br/>        if isinstance(status, int):<br/>            value_json = response.get(&quot;value&quot;, None)<br/>            if value_json and isinstance(value_json, str):<br/>                import json<br/>    <br/>                try:<br/>                    value = json.loads(value_json)<br/>                    if len(value) == 1:<br/>                        value = value[&quot;value&quot;]<br/>                    status = value.get(&quot;error&quot;, None)<br/>                    if not status:<br/>                        status = value.get(&quot;status&quot;, ErrorCode.UNKNOWN_ERROR)<br/>                        message = value.get(&quot;value&quot;) or value.get(&quot;message&quot;)<br/>                        if not isinstance(message, str):<br/>                            value = message<br/>                            message = message.get(&quot;message&quot;)<br/>                    else:<br/>                        message = value.get(&quot;message&quot;, None)<br/>                except ValueError:<br/>                    pass<br/>    <br/>        exception_class: Type[WebDriverException]<br/>        if status in ErrorCode.NO_SUCH_ELEMENT:<br/>            exception_class = NoSuchElementException<br/>        elif status in ErrorCode.NO_SUCH_FRAME:<br/>            exception_class = NoSuchFrameException<br/>        elif status in ErrorCode.NO_SUCH_SHADOW_ROOT:<br/>            exception_class = NoSuchShadowRootException<br/>        elif status in ErrorCode.NO_SUCH_WINDOW:<br/>            exception_class = NoSuchWindowException<br/>        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:<br/>            exception_class = StaleElementReferenceException<br/>        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:<br/>            exception_class = ElementNotVisibleException<br/>        elif status in ErrorCode.INVALID_ELEMENT_STATE:<br/>            exception_class = InvalidElementStateException<br/>        elif (<br/>            status in ErrorCode.INVALID_SELECTOR<br/>            or status in ErrorCode.INVALID_XPATH_SELECTOR<br/>            or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER<br/>        ):<br/>            exception_class = InvalidSelectorException<br/>        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:<br/>            exception_class = ElementNotSelectableException<br/>        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:<br/>            exception_class = ElementNotInteractableException<br/>        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:<br/>            exception_class = InvalidCookieDomainException<br/>        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:<br/>            exception_class = UnableToSetCookieException<br/>        elif status in ErrorCode.TIMEOUT:<br/>            exception_class = TimeoutException<br/>        elif status in ErrorCode.SCRIPT_TIMEOUT:<br/>            exception_class = TimeoutException<br/>        elif status in ErrorCode.UNKNOWN_ERROR:<br/>            exception_class = WebDriverException<br/>        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:<br/>            exception_class = UnexpectedAlertPresentException<br/>        elif status in ErrorCode.NO_ALERT_OPEN:<br/>            exception_class = NoAlertPresentException<br/>        elif status in ErrorCode.IME_NOT_AVAILABLE:<br/>            exception_class = ImeNotAvailableException<br/>        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:<br/>            exception_class = ImeActivationFailedException<br/>        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:<br/>            exception_class = MoveTargetOutOfBoundsException<br/>        elif status in ErrorCode.JAVASCRIPT_ERROR:<br/>            exception_class = JavascriptException<br/>        elif status in ErrorCode.SESSION_NOT_CREATED:<br/>            exception_class = SessionNotCreatedException<br/>        elif status in ErrorCode.INVALID_ARGUMENT:<br/>            exception_class = InvalidArgumentException<br/>        elif status in ErrorCode.NO_SUCH_COOKIE:<br/>            exception_class = NoSuchCookieException<br/>        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:<br/>            exception_class = ScreenshotException<br/>        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:<br/>            exception_class = ElementClickInterceptedException<br/>        elif status in ErrorCode.INSECURE_CERTIFICATE:<br/>            exception_class = InsecureCertificateException<br/>        elif status in ErrorCode.INVALID_COORDINATES:<br/>            exception_class = InvalidCoordinatesException<br/>        elif status in ErrorCode.INVALID_SESSION_ID:<br/>            exception_class = InvalidSessionIdException<br/>        elif status in ErrorCode.UNKNOWN_METHOD:<br/>            exception_class = UnknownMethodException<br/>        else:<br/>            exception_class = WebDriverException<br/>        if not value:<br/>            value = response[&quot;value&quot;]<br/>        if isinstance(value, str):<br/>            raise exception_class(value)<br/>        if message == &quot;&quot; and &quot;message&quot; in value:<br/>            message = value[&quot;message&quot;]<br/>    <br/>        screen = None  # type: ignore[assignment]<br/>        if &quot;screen&quot; in value:<br/>            screen = value[&quot;screen&quot;]<br/>    <br/>        stacktrace = None<br/>        st_value = value.get(&quot;stackTrace&quot;) or value.get(&quot;stacktrace&quot;)<br/>        if st_value:<br/>            if isinstance(st_value, str):<br/>                stacktrace = st_value.split(&quot;\n&quot;)<br/>            else:<br/>                stacktrace = []<br/>                try:<br/>                    for frame in st_value:<br/>                        line = frame.get(&quot;lineNumber&quot;, &quot;&quot;)<br/>                        file = frame.get(&quot;fileName&quot;, &quot;&lt;anonymous&gt;&quot;)<br/>                        if line:<br/>                            file = f&quot;{file}:{line}&quot;<br/>                        meth = frame.get(&quot;methodName&quot;, &quot;&lt;anonymous&gt;&quot;)<br/>                        if &quot;className&quot; in frame:<br/>                            meth = f&quot;{frame[&#x27;className&#x27;]}.{meth}&quot;<br/>                        msg = &quot;    at %s (%s)&quot;<br/>                        msg = msg % (meth, file)<br/>                        stacktrace.append(msg)<br/>                except TypeError:<br/>                    pass<br/>        if exception_class == UnexpectedAlertPresentException:<br/>            alert_text = None<br/>            if &quot;data&quot; in value:<br/>                alert_text = value[&quot;data&quot;].get(&quot;text&quot;)<br/>            elif &quot;alert&quot; in value:<br/>                alert_text = value[&quot;alert&quot;].get(&quot;text&quot;)<br/>            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here<br/>&gt;       raise exception_class(message, screen, stacktrace)<br/><span class="error">E       selenium.common.exceptions.ElementNotInteractableException: Message: Element &lt;button class=&quot;_35coK uui-button-box uui-enabled -clickable _2DnCG _150pO _20Vp7&quot;&gt; could not be scrolled into view</span><br/><span class="error">E       Stacktrace:</span><br/><span class="error">E       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8</span><br/><span class="error">E       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5</span><br/><span class="error">E       ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:290:5</span><br/><span class="error">E       webdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:150:11</span><br/><span class="error">E       interaction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:119:11</span><br/><span class="error">E       clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:208:29</span><br/><span class="error">E       receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:97:31</span><br/><br/>F:\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py:245: ElementNotInteractableException<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, 1.14MB/s]                                                                                                                                                                                   
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_smoke_feedback_empty_form_submits</td>
          <td class="col-duration">15.51</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;test_main.TestFeedbackForm object at 0x000001E039347350&gt;, browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;0394378a-9d86-468a-aff9-9f5128dcd798&quot;)&gt;, feedback = None<br/>feedback_database_setup = &lt;sqlalchemy.engine.base.Connection object at 0x000001E0393AC1D0&gt;<br/><br/>    @pytest.mark.smoke<br/>    def test_smoke_feedback_empty_form_submits(self, browser, feedback, feedback_database_setup):<br/>        wait = WebDriverWait(browser, 20)<br/>    <br/>        # Open Feedback form (by feedback as a function arg)<br/>    <br/>        # Check if opened dialog title is displayed:<br/>        assert browser.find_element(By.CSS_SELECTOR, &#x27;.ant-modal-root&#x27;).is_displayed()<br/>    <br/>        # # Click on #1 scale button:<br/>        try:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point1&quot;]&#x27;)<br/>            )).click()<br/>        except:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point1&quot;] &gt; div&#x27;)<br/>            )).click()<br/>    <br/>        # Click on &quot;Send&quot; button:<br/>        wait.until(EC.element_to_be_clickable(<br/>            (By.CSS_SELECTOR, &#x27;.ant-modal-footer .Button__button.Button__limeGreen&#x27;)<br/>        )).click()<br/>    <br/>        # Check if Successful message appeared:<br/>        displayed_message = wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;.uui-snackbar-item-self&gt;div&gt;div&gt;div&gt;div&#x27;)<br/>        )).text<br/>        correct_message = &#x27;Your feedback has been submitted. Thank you!&#x27;<br/>&gt;       assert displayed_message == correct_message, \<br/>            f&#x27;Incorrect Successful message - &quot;{displayed_message}&quot; instead of &quot;{correct_message}&quot;&#x27;<br/><span class="error">E       AssertionError: Incorrect Successful message - &quot;&quot; instead of &quot;Your feedback has been submitted. Thank you!&quot;</span><br/><span class="error">E       assert &#x27;&#x27; == &#x27;Your feedbac...d. Thank you!&#x27;</span><br/><span class="error">E         - Your feedback has been submitted. Thank you!</span><br/><br/>test_main.py:40: AssertionError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_feedback_form_scale_check[2]</td>
          <td class="col-duration">14.53</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;test_main.TestFeedbackForm object at 0x000001E039348790&gt;, browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;38ce4402-706f-4d24-aee7-1681aa04ffb4&quot;)&gt;, feedback = None<br/>feedback_database_setup = &lt;sqlalchemy.engine.base.Connection object at 0x000001E03A8F97D0&gt;, scale = 2<br/><br/>    @pytest.mark.feedbacksymbolslimit<br/>    @pytest.mark.parametrize(&quot;scale&quot;, range(2, 11))<br/>    def test_feedback_form_scale_check(self, browser, feedback, feedback_database_setup, scale):<br/>        wait = WebDriverWait(browser, 20)<br/>    <br/>        # Open Feedback form (by feedback as a function arg)<br/>    <br/>        # # Click on scale button:<br/>        try:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;]&#x27;)<br/>            )).click()<br/>        except:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;] &gt; div&#x27;)<br/>            )).click()<br/>    <br/>        # Click on &quot;Send&quot; button:<br/>        wait.until(EC.element_to_be_clickable(<br/>            (By.CSS_SELECTOR, &#x27;.ant-modal-footer .Button__button.Button__limeGreen&#x27;)<br/>        )).click()<br/>    <br/>        # Check if Successful message appeared:<br/>        displayed_message = wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;.uui-snackbar-item-self&gt;div&gt;div&gt;div&gt;div&#x27;)<br/>        )).text<br/>        correct_message = &#x27;Your feedback has been submitted. Thank you!&#x27;<br/>&gt;       assert displayed_message == correct_message, \<br/>            f&#x27;Incorrect Successful message - &quot;{displayed_message}&quot; instead of &quot;{correct_message}&quot;&#x27;<br/><span class="error">E       AssertionError: Incorrect Successful message - &quot;&quot; instead of &quot;Your feedback has been submitted. Thank you!&quot;</span><br/><span class="error">E       assert &#x27;&#x27; == &#x27;Your feedbac...d. Thank you!&#x27;</span><br/><span class="error">E         - Your feedback has been submitted. Thank you!</span><br/><br/>test_main.py:76: AssertionError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.88k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_feedback_form_scale_check[4]</td>
          <td class="col-duration">15.13</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;test_main.TestFeedbackForm object at 0x000001E039348C90&gt;, browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;4185c959-f501-4b27-8d60-39235d3a14e3&quot;)&gt;, feedback = None<br/>feedback_database_setup = &lt;sqlalchemy.engine.base.Connection object at 0x000001E03B00C790&gt;, scale = 4<br/><br/>    @pytest.mark.feedbacksymbolslimit<br/>    @pytest.mark.parametrize(&quot;scale&quot;, range(2, 11))<br/>    def test_feedback_form_scale_check(self, browser, feedback, feedback_database_setup, scale):<br/>        wait = WebDriverWait(browser, 20)<br/>    <br/>        # Open Feedback form (by feedback as a function arg)<br/>    <br/>        # # Click on scale button:<br/>        try:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;]&#x27;)<br/>            )).click()<br/>        except:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;] &gt; div&#x27;)<br/>            )).click()<br/>    <br/>        # Click on &quot;Send&quot; button:<br/>        wait.until(EC.element_to_be_clickable(<br/>            (By.CSS_SELECTOR, &#x27;.ant-modal-footer .Button__button.Button__limeGreen&#x27;)<br/>        )).click()<br/>    <br/>        # Check if Successful message appeared:<br/>        displayed_message = wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;.uui-snackbar-item-self&gt;div&gt;div&gt;div&gt;div&#x27;)<br/>        )).text<br/>        correct_message = &#x27;Your feedback has been submitted. Thank you!&#x27;<br/>&gt;       assert displayed_message == correct_message, \<br/>            f&#x27;Incorrect Successful message - &quot;{displayed_message}&quot; instead of &quot;{correct_message}&quot;&#x27;<br/><span class="error">E       AssertionError: Incorrect Successful message - &quot;&quot; instead of &quot;Your feedback has been submitted. Thank you!&quot;</span><br/><span class="error">E       assert &#x27;&#x27; == &#x27;Your feedbac...d. Thank you!&#x27;</span><br/><span class="error">E         - Your feedback has been submitted. Thank you!</span><br/><br/>test_main.py:76: AssertionError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_feedback_form_scale_check[6]</td>
          <td class="col-duration">14.93</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;test_main.TestFeedbackForm object at 0x000001E039349210&gt;, browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;cbe24699-ea19-43c3-97f7-cd907c192e9d&quot;)&gt;, feedback = None<br/>feedback_database_setup = &lt;sqlalchemy.engine.base.Connection object at 0x000001E03B11FBD0&gt;, scale = 6<br/><br/>    @pytest.mark.feedbacksymbolslimit<br/>    @pytest.mark.parametrize(&quot;scale&quot;, range(2, 11))<br/>    def test_feedback_form_scale_check(self, browser, feedback, feedback_database_setup, scale):<br/>        wait = WebDriverWait(browser, 20)<br/>    <br/>        # Open Feedback form (by feedback as a function arg)<br/>    <br/>        # # Click on scale button:<br/>        try:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;]&#x27;)<br/>            )).click()<br/>        except:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;] &gt; div&#x27;)<br/>            )).click()<br/>    <br/>        # Click on &quot;Send&quot; button:<br/>        wait.until(EC.element_to_be_clickable(<br/>            (By.CSS_SELECTOR, &#x27;.ant-modal-footer .Button__button.Button__limeGreen&#x27;)<br/>        )).click()<br/>    <br/>        # Check if Successful message appeared:<br/>        displayed_message = wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;.uui-snackbar-item-self&gt;div&gt;div&gt;div&gt;div&#x27;)<br/>        )).text<br/>        correct_message = &#x27;Your feedback has been submitted. Thank you!&#x27;<br/>&gt;       assert displayed_message == correct_message, \<br/>            f&#x27;Incorrect Successful message - &quot;{displayed_message}&quot; instead of &quot;{correct_message}&quot;&#x27;<br/><span class="error">E       AssertionError: Incorrect Successful message - &quot;&quot; instead of &quot;Your feedback has been submitted. Thank you!&quot;</span><br/><span class="error">E       assert &#x27;&#x27; == &#x27;Your feedbac...d. Thank you!&#x27;</span><br/><span class="error">E         - Your feedback has been submitted. Thank you!</span><br/><br/>test_main.py:76: AssertionError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_feedback_form_scale_check[7]</td>
          <td class="col-duration">14.79</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;test_main.TestFeedbackForm object at 0x000001E039349650&gt;, browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;5a4ebeb2-c85d-4388-b689-5c3369c9bd0a&quot;)&gt;, feedback = None<br/>feedback_database_setup = &lt;sqlalchemy.engine.base.Connection object at 0x000001E03A935950&gt;, scale = 7<br/><br/>    @pytest.mark.feedbacksymbolslimit<br/>    @pytest.mark.parametrize(&quot;scale&quot;, range(2, 11))<br/>    def test_feedback_form_scale_check(self, browser, feedback, feedback_database_setup, scale):<br/>        wait = WebDriverWait(browser, 20)<br/>    <br/>        # Open Feedback form (by feedback as a function arg)<br/>    <br/>        # # Click on scale button:<br/>        try:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;]&#x27;)<br/>            )).click()<br/>        except:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;] &gt; div&#x27;)<br/>            )).click()<br/>    <br/>        # Click on &quot;Send&quot; button:<br/>        wait.until(EC.element_to_be_clickable(<br/>            (By.CSS_SELECTOR, &#x27;.ant-modal-footer .Button__button.Button__limeGreen&#x27;)<br/>        )).click()<br/>    <br/>        # Check if Successful message appeared:<br/>        displayed_message = wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;.uui-snackbar-item-self&gt;div&gt;div&gt;div&gt;div&#x27;)<br/>        )).text<br/>        correct_message = &#x27;Your feedback has been submitted. Thank you!&#x27;<br/>&gt;       assert displayed_message == correct_message, \<br/>            f&#x27;Incorrect Successful message - &quot;{displayed_message}&quot; instead of &quot;{correct_message}&quot;&#x27;<br/><span class="error">E       AssertionError: Incorrect Successful message - &quot;&quot; instead of &quot;Your feedback has been submitted. Thank you!&quot;</span><br/><span class="error">E       assert &#x27;&#x27; == &#x27;Your feedbac...d. Thank you!&#x27;</span><br/><span class="error">E         - Your feedback has been submitted. Thank you!</span><br/><br/>test_main.py:76: AssertionError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_feedback_form_scale_check[8]</td>
          <td class="col-duration">14.92</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;test_main.TestFeedbackForm object at 0x000001E039349990&gt;, browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;7384b2ce-e968-492d-99b8-9c06d3e661d4&quot;)&gt;, feedback = None<br/>feedback_database_setup = &lt;sqlalchemy.engine.base.Connection object at 0x000001E0393AD250&gt;, scale = 8<br/><br/>    @pytest.mark.feedbacksymbolslimit<br/>    @pytest.mark.parametrize(&quot;scale&quot;, range(2, 11))<br/>    def test_feedback_form_scale_check(self, browser, feedback, feedback_database_setup, scale):<br/>        wait = WebDriverWait(browser, 20)<br/>    <br/>        # Open Feedback form (by feedback as a function arg)<br/>    <br/>        # # Click on scale button:<br/>        try:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;]&#x27;)<br/>            )).click()<br/>        except:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;] &gt; div&#x27;)<br/>            )).click()<br/>    <br/>        # Click on &quot;Send&quot; button:<br/>        wait.until(EC.element_to_be_clickable(<br/>            (By.CSS_SELECTOR, &#x27;.ant-modal-footer .Button__button.Button__limeGreen&#x27;)<br/>        )).click()<br/>    <br/>        # Check if Successful message appeared:<br/>        displayed_message = wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;.uui-snackbar-item-self&gt;div&gt;div&gt;div&gt;div&#x27;)<br/>        )).text<br/>        correct_message = &#x27;Your feedback has been submitted. Thank you!&#x27;<br/>&gt;       assert displayed_message == correct_message, \<br/>            f&#x27;Incorrect Successful message - &quot;{displayed_message}&quot; instead of &quot;{correct_message}&quot;&#x27;<br/><span class="error">E       AssertionError: Incorrect Successful message - &quot;&quot; instead of &quot;Your feedback has been submitted. Thank you!&quot;</span><br/><span class="error">E       assert &#x27;&#x27; == &#x27;Your feedbac...d. Thank you!&#x27;</span><br/><span class="error">E         - Your feedback has been submitted. Thank you!</span><br/><br/>test_main.py:76: AssertionError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_feedback_form_scale_check[9]</td>
          <td class="col-duration">14.48</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;test_main.TestFeedbackForm object at 0x000001E039349CD0&gt;, browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;798dc64e-3642-48a5-aaf4-0f5d2a3bdd98&quot;)&gt;, feedback = None<br/>feedback_database_setup = &lt;sqlalchemy.engine.base.Connection object at 0x000001E03ADE7310&gt;, scale = 9<br/><br/>    @pytest.mark.feedbacksymbolslimit<br/>    @pytest.mark.parametrize(&quot;scale&quot;, range(2, 11))<br/>    def test_feedback_form_scale_check(self, browser, feedback, feedback_database_setup, scale):<br/>        wait = WebDriverWait(browser, 20)<br/>    <br/>        # Open Feedback form (by feedback as a function arg)<br/>    <br/>        # # Click on scale button:<br/>        try:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;]&#x27;)<br/>            )).click()<br/>        except:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;] &gt; div&#x27;)<br/>            )).click()<br/>    <br/>        # Click on &quot;Send&quot; button:<br/>        wait.until(EC.element_to_be_clickable(<br/>            (By.CSS_SELECTOR, &#x27;.ant-modal-footer .Button__button.Button__limeGreen&#x27;)<br/>        )).click()<br/>    <br/>        # Check if Successful message appeared:<br/>        displayed_message = wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;.uui-snackbar-item-self&gt;div&gt;div&gt;div&gt;div&#x27;)<br/>        )).text<br/>        correct_message = &#x27;Your feedback has been submitted. Thank you!&#x27;<br/>&gt;       assert displayed_message == correct_message, \<br/>            f&#x27;Incorrect Successful message - &quot;{displayed_message}&quot; instead of &quot;{correct_message}&quot;&#x27;<br/><span class="error">E       AssertionError: Incorrect Successful message - &quot;&quot; instead of &quot;Your feedback has been submitted. Thank you!&quot;</span><br/><span class="error">E       assert &#x27;&#x27; == &#x27;Your feedbac...d. Thank you!&#x27;</span><br/><span class="error">E         - Your feedback has been submitted. Thank you!</span><br/><br/>test_main.py:76: AssertionError<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_feedback_form_scale_check[10]</td>
          <td class="col-duration">14.59</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;test_main.TestFeedbackForm object at 0x000001E03934A010&gt;, browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;b2d60d99-3475-422a-8777-b187d2a6200a&quot;)&gt;, feedback = None<br/>feedback_database_setup = &lt;sqlalchemy.engine.base.Connection object at 0x000001E03A906790&gt;, scale = 10<br/><br/>    @pytest.mark.feedbacksymbolslimit<br/>    @pytest.mark.parametrize(&quot;scale&quot;, range(2, 11))<br/>    def test_feedback_form_scale_check(self, browser, feedback, feedback_database_setup, scale):<br/>        wait = WebDriverWait(browser, 20)<br/>    <br/>        # Open Feedback form (by feedback as a function arg)<br/>    <br/>        # # Click on scale button:<br/>        try:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;]&#x27;)<br/>            )).click()<br/>        except:<br/>            wait.until(EC.element_to_be_clickable(<br/>                (By.CSS_SELECTOR, f&#x27;label[for=&quot;point{scale}&quot;] &gt; div&#x27;)<br/>            )).click()<br/>    <br/>        # Click on &quot;Send&quot; button:<br/>        wait.until(EC.element_to_be_clickable(<br/>            (By.CSS_SELECTOR, &#x27;.ant-modal-footer .Button__button.Button__limeGreen&#x27;)<br/>        )).click()<br/>    <br/>        # Check if Successful message appeared:<br/>        displayed_message = wait.until(EC.presence_of_element_located(<br/>            (By.CSS_SELECTOR, &#x27;.uui-snackbar-item-self&gt;div&gt;div&gt;div&gt;div&#x27;)<br/>        )).text<br/>        correct_message = &#x27;Your feedback has been submitted. Thank you!&#x27;<br/>&gt;       assert displayed_message == correct_message, \<br/>            f&#x27;Incorrect Successful message - &quot;{displayed_message}&quot; instead of &quot;{correct_message}&quot;&#x27;<br/><span class="error">E       AssertionError: Incorrect Successful message - &quot;&quot; instead of &quot;Your feedback has been submitted. Thank you!&quot;</span><br/><span class="error">E       assert &#x27;&#x27; == &#x27;Your feedbac...d. Thank you!&#x27;</span><br/><span class="error">E         - Your feedback has been submitted. Thank you!</span><br/><br/>test_main.py:76: AssertionError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody>
      <tbody class="xfailed results-table-row">
        <tr>
          <td class="col-result">XFailed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_5247_feedback_input_not_allowed_limit</td>
          <td class="col-duration">14.55</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">self = &lt;test_main.TestFeedbackForm object at 0x000001E03934B550&gt;, browser = &lt;selenium.webdriver.firefox.webdriver.WebDriver (session=&quot;dd0cb28e-2446-4f52-898b-9b53ad5297f9&quot;)&gt;, feedback = None<br/><br/>    @pytest.mark.xfail<br/>    @pytest.mark.feedbacksymbolslimit<br/>    def test_5247_feedback_input_not_allowed_limit(self, browser, feedback):<br/>    <br/>        # Perform feedback<br/>    <br/>        # Put 256 symbols into input field:<br/>        input_field = browser.find_element(By.CSS_SELECTOR, &#x27;textarea[data-testid=&quot;feedback-comment-field&quot;]&#x27;)<br/>        input_field.send_keys(FEEDBACK_INPUT[&#x27;256&#x27;])<br/>    <br/>        # Check if input field have not received 256 symbols:<br/>&gt;       assert len(input_field.text) == 255, f&#x27;Error - length is {len(input_field.text)} instead of 255 max allowed&#x27;<br/><span class="error">E       AssertionError: Error - length is 256 instead of 255 max allowed</span><br/><span class="error">E       assert 256 == 255</span><br/><span class="error">E        +  where 256 = len(&#x27;Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis ...magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis12&#x27;)</span><br/><span class="error">E        +    where &#x27;Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis ...magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis12&#x27; = &lt;selenium.webdriver.remote.webelement.WebElement (session=&quot;dd0cb28e-2446-4f52-898b-9b53ad5297f9&quot;, element=&quot;2e727a96-2240-471d-8347-9347ef5ccb5a&quot;)&gt;.text</span><br/><br/>test_main.py:127: AssertionError<br/> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_main.py::TestFeedbackForm::test_5246_feedback_input_allowed_limit[255]</td>
          <td class="col-duration">15.24</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> -----------------------------Captured stderr setup------------------------------ <br/>[WDM] - Downloading:   0%|                                                                                                                                                                          | 0.00/1.89k [00:00&lt;?, ?B/s][WDM] - Downloading: 17.4kB [00:00, ?B/s]                                                                                                                                                                                       
<br/></div></td></tr></tbody></table></body></html>